#!/bin/bash

# Hugging Face Deployment Script for AI Assistant Backend

set -e

echo "🤗 Deploying AI Assistant Backend with Hugging Face..."
echo "====================================================="
echo ""

# Get the current directory
BACKEND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "📁 Backend directory: $BACKEND_DIR"
echo ""

echo "📋 Prerequisites Checklist:"
echo "✅ Backend code ready (Hugging Face version)"
echo "✅ railway.json configured"
echo "✅ requirements.txt present"
echo "✅ app.py configured for Hugging Face"
echo ""

echo "🌐 Next Steps:"
echo ""
echo "1. Get Hugging Face API Key:"
echo "   - Go to https://huggingface.co"
echo "   - Sign up for free account"
echo "   - Go to Settings → Access Tokens"
echo "   - Create new token with 'Read' permissions"
echo "   - Copy the token (starts with 'hf_')"
echo ""
echo "2. Deploy to Railway:"
echo "   - Go to https://railway.app"
echo "   - Sign up with GitHub"
echo "   - Create new project"
echo "   - Select 'Deploy from GitHub repo'"
echo "   - Choose: francesco-innocenti.github.io"
echo "   - Set root directory: backend"
echo ""
echo "3. Configure environment variables:"
echo "   - HF_API_KEY=hf_your_token_here"
echo "   - MODEL_NAME=microsoft/DialoGPT-medium"
echo "   - FLASK_ENV=production"
echo "   - PORT=10000"
echo ""
echo "4. Update frontend config:"
echo "   - Edit _pages/ai-assistant-config.js"
echo "   - Set API_URL to your Railway backend URL"
echo ""
echo "5. Commit and push:"
echo "    git add ."
echo "    git commit -m 'Configure for Hugging Face deployment'"
echo "    git push origin main"
echo ""

echo "🔧 Railway CLI Commands (Optional):"
echo ""
echo "Install Railway CLI:"
echo "  npm install -g @railway/cli"
echo ""
echo "Login and deploy:"
echo "  railway login"
echo "  railway link"
echo "  railway up"
echo ""

echo "📚 For detailed instructions, see:"
echo "   - HUGGINGFACE_DEPLOYMENT.md"
echo "   - GITHUB_PAGES_SETUP.md"
echo ""

echo "🔗 Useful Links:"
echo "   - Hugging Face: https://huggingface.co"
echo "   - Railway Dashboard: https://railway.app/dashboard"
echo "   - Your Repository: https://github.com/francesco-innocenti/francesco-innocenti.github.io"
echo ""

echo "🎉 Ready to deploy! Follow the steps above to get your AI Assistant running with Hugging Face."
echo ""
echo "💡 Pro Tip: Hugging Face offers 30,000 free requests per month - perfect for personal use!"
