version: '3.8'

services:
  ollama-service:
    build:
      context: ..
      dockerfile: backend/ollama.Dockerfile
    ports:
      - "11434:11434"
    environment:
      - MODEL_NAME=phi3:mini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  flask-app:
    build:
      context: ..
      dockerfile: backend/flask-app.Dockerfile
    ports:
      - "5001:5001"
    environment:
      - OLLAMA_BASE_URL=http://ollama-service:11434
      - MODEL_NAME=phi3:mini
      - PORT=5001
    depends_on:
      ollama-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
